import type { FieldReport } from "./types";

export const mockMobileReports: FieldReport[] = [
  {
    id: "fr-001",
    timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
    personnelName: "Bripka Yohanis",
    nrp: "85020112",
    locationName: "Pasar Oeba, Kupang",
    lat: -10.1712,
    lng: 123.5850,
    textReport: "Situasi pasar ramai menjelang sore. Tidak ada indikasi gangguan keamanan. Pedagang beroperasi normal.",
    imageSrc: "",
    yoloBoxes: [],
  },
  {
    id: "fr-002",
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
    personnelName: "Aipda Rahmat",
    nrp: "88090334",
    locationName: "Bundaran PU, Kupang",
    lat: -10.1623,
    lng: 123.6014,
    textReport: "Terdeteksi kerumunan massa di sekitar bundaran. Estimasi 200 orang. Membawa spanduk. Situasi masih terkendali.",
    imageSrc: "",
    yoloBoxes: [
      { label: "Massa", confidence: 0.95, x: 10, y: 15, width: 60, height: 70 },
      { label: "Spanduk", confidence: 0.88, x: 30, y: 5, width: 40, height: 20 },
    ],
  },
  {
    id: "fr-003",
    timestamp: new Date(Date.now() - 3 * 60000).toISOString(),
    personnelName: "Brigadir Stefanus",
    nrp: "92040556",
    locationName: "Pelabuhan Labuan Bajo",
    lat: -8.4966,
    lng: 119.8773,
    textReport: "Patroli rutin di area pelabuhan wisata. Satu individu mencurigakan terdeteksi membawa sajam. Sudah diamankan.",
    imageSrc: "",
    yoloBoxes: [
      { label: "Sajam", confidence: 0.91, x: 55, y: 40, width: 15, height: 25 },
      { label: "Individu", confidence: 0.97, x: 40, y: 20, width: 30, height: 60 },
    ],
  },
  {
    id: "fr-004",
    timestamp: new Date(Date.now() - 1 * 60000).toISOString(),
    personnelName: "Briptu Daniel",
    nrp: "94010778",
    locationName: "Desa Wolomeze, Ngada",
    lat: -8.7800,
    lng: 121.0500,
    textReport: "SOS – Konflik horizontal antar warga. Personil membutuhkan bantuan segera.",
    imageSrc: "",
    yoloBoxes: [],
    isSOS: true,
  },
];
