import type { FieldReport } from "./types";

export const mockMobileReports: FieldReport[] = [
  {
    id: "fr-001",
    personnelId: "P-001",
    personnelName: "Bripda Andi",
    lat: -10.158,
    lng: 123.606,
    timestamp: new Date().toISOString(),
    textReport: "Patroli rutin di sektor Wolomeze. Tidak ada aktivitas mencurigakan.",
    batteryLevel: 85,
    isSOS: false,
    isFakeGPS: false,
    isUndercover: false,
  },
  {
    id: "fr-002",
    personnelId: "P-002",
    personnelName: "Bp. Terawan",
    lat: -10.165,
    lng: 123.615,
    timestamp: new Date().toISOString(),
    textReport: "Area Pasar Oeba ramai. Memerluhkan penguatan di titik keramaian.",
    batteryLevel: 72,
    isSOS: false,
    isFakeGPS: false,
    isUndercover: false,
  },
  {
    id: "fr-003",
    personnelId: "P-003",
    personnelName: "Bripka Yohanis",
    lat: -10.170,
    lng: 123.598,
    timestamp: new Date().toISOString(),
    textReport: "Kecepatan tinggi di jalur Soe. Melebihi batas kecepatan 80km/jam.",
    batteryLevel: 45,
    isSOS: false,
    isFakeGPS: false,
    isUndercover: false,
  },
  {
    id: "fr-004",
    personnelId: "P-004",
    personnelName: "Unit Daniel",
    lat: -10.162,
    lng: 123.620,
    timestamp: new Date().toISOString(),
    textReport: "GEOFENCE BREACH - Outside Wolomeze boundary!",
    batteryLevel: 12,
    isSOS: false,
    isFakeGPS: true,
    isUndercover: false,
  },
  {
    id: "fr-005",
    personnelId: "P-005",
    personnelName: "Operasi Siluman",
    lat: -10.175,
    lng: 123.590,
    timestamp: new Date().toISOString(),
    textReport: "Mode undercover aktif. Laporan diam-diam.",
    batteryLevel: 91,
    isSOS: false,
    isFakeGPS: false,
    isUndercover: true,
  },
];
