"use client";

import React from "react";
import { Settings } from "lucide-react";

import AuditLogTable from "@/components/analytics/AuditLogTable";

export default function AnevView() {
  return (
    <div className="p-3 sm:p-6 md:p-10 h-full flex flex-col w-full bg-[#07111F] overflow-y-auto custom-scrollbar">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h2 className="text-2xl sm:text-3xl font-black text-white uppercase tracking-tighter italic">Tactical Audit & Anev</h2>
          <p className="text-slate-500 text-xs sm:text-sm uppercase font-bold tracking-[0.2em] mt-1">Operational Security Logging System • BIRO OPS POLDA NTT</p>
        </div>
        <div className="hidden md:flex items-center gap-2 px-4 py-2 bg-[#D4AF37]/10 border border-[#D4AF37]/30 rounded-xl">
          <Settings size={16} className="text-[#D4AF37] animate-spin-slow" />
          <span className="text-[#D4AF37] text-[10px] font-black uppercase tracking-widest">AI Summary Active</span>
        </div>
      </div>

      <div className="mb-8 bg-[#0B1B32] border border-white/10 rounded-2xl p-5 md:p-6 shadow-xl relative overflow-hidden">
        <div className="absolute top-0 left-0 w-1 h-full bg-[#D4AF37]" />
        <h3 className="text-sm font-black text-white uppercase tracking-widest mb-3 flex items-center gap-2">
          Daily Executive Narrative
        </h3>
        <p className="text-sm text-slate-300 leading-relaxed font-mono">
          Berdasarkan analisis Turangga-AI terhadap data operasional 24 jam terakhir: Terjadi lonjakan <strong className="text-red-400">Kasus Laka Lantas sebesar 15%</strong> di area Kupang Kota dan Oesapa. Analisis korelasi menemukan bahwa peningkatan ini sejalan dengan <span className="text-blue-400">hujan deras dan minimnya penerangan jalan</span> di titik-titik tersebut. Sementara itu, tingkat penyelesaian kasus (Crime Clearance) di sektor perbatasan menunjukkan tren positif (+8%) berkat peningkatan frekuensi patroli preventif.
        </p>
        <div className="mt-4 pt-4 border-t border-white/5 flex gap-4">
          <div className="text-[10px] text-slate-500 font-mono uppercase">Generated by: Turangga-AI</div>
          <div className="text-[10px] text-slate-500 font-mono uppercase">Confidence: 94.2%</div>
        </div>
      </div>
      
      <div className="flex-1">
        <AuditLogTable />
      </div>
    </div>
  );
}
